### ISSUE TITLE
OverflowError: can't convert negative value to uint32_t

### ISSUE THREAD

**Issue by ZunsongHu** [ylab-hi/ScanITD#4]
Hi, can ScanITD be used for RNAseq data? I used the bam file mapping with STAR  but got the following errors:

Traceback (most recent call last):
  File "/home/zgu_labs/bin/ScanITD.py", line 552, in <module>
    main()
  File "/home/zgu_labs/bin/ScanITD.py", line 525, in main
    softclipping_realignment(mapq_cutoff=options.mapq, input=options.input, output=itd_build)
  File "/home/zgu_labs/bin/ScanITD.py", line 156, in softclipping_realignment
    read.cigar, read.pos = newcigar, newpos
  File "pysam/libcalignedsegment.pyx", line 2652, in pysam.libcalignedsegment.AlignedSegment.cigar.__set__
  File "pysam/libcalignedsegment.pyx", line 2224, in pysam.libcalignedsegment.AlignedSegment.cigartuples.__set__
OverflowError: can't convert negative value to uint32_t

Thank you very much!

**Comment by dolittle007** [comment]
ScanITD cannot be employed for RNA-Seq data. 
According to your error message, it seems that something is wrong with your BAM format.
